version: '3'

services:
 nginx:
    container_name: nginx
    image: nginx:alpine
    user: 0:0 #user root
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./iconf.d:/etc/nginx/conf.d #mapeamento arquivo de configuração
